# Generated by Django 4.0.4 on 2022-05-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_numbers", "0002_remove_post_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="telephone_number",
        ),
        migrations.RemoveField(
            model_name="post",
            name="telephone_prefix",
        ),
    ]
