# Generated by Django 4.0.1 on 2022-03-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.category')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.user')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('telephone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('prefix', models.IntegerField()),
            ],
            options={
                'unique_together': {('phone', 'prefix')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='creation_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='telephone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.telephone'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataNumbers.user')),
            ],
        ),
    ]
